### ISSUE TITLE
Bot sostituito

### ISSUE THREAD

**Issue by MarcoBuster** [lollofra/IATA-Support-BOT#1]
Questo bot è stato sostituito da [IATA-bot](www.github.com/IATAdev/IATA-bot), quindi chiedo la rimozione della repostory, @lollofra

**Comment by lollofra** [comment]
Per me i sorgenti devono rimanere disponibili

**Comment by MarcoBuster** [comment]
@lollofra Se questo bot sarà sostituito no, anche perchè è una versione datata non utile a nessuno @lollofra

**Comment by MarcoBuster** [comment]
@lollofra Si crea poi solo confusione tra i vari sorgenti

**Comment by lollofra** [comment]
E se poi te ne penti?

**Comment by MarcoBuster** [comment]
@lollofra Clonala in locale e non te ne pentirai :)

**Comment by lollofra** [comment]
![penti](https://cloud.githubusercontent.com/assets/17254822/18419120/5cdc783a-7854-11e6-9feb-e54bb8932adb.gif)

**Comment by MarcoBuster** [comment]
Laddroga

**Comment by giuseppeM99** [comment]
@lollofra ho una copia dei sorgenti nell'archivio, puoi elimiare la repo se vuoi

**Comment by MarcoBuster** [comment]
@giuseppeM99 @lollofra elimina la Repo!

**Comment by giuseppeM99** [comment]
@MarcoBuster @lollofra proporrei di mettere nel readme e nel titolo un
 **DEPRECATED**
The new bot is [IATA-bot](https://github.com/IATAdev/IATA-bot), you can find it [@iata_bot](https://telegram.me/iata_bot)

**Comment by MarcoBuster** [comment]
@giuseppeM99 O di eliminare proprio la Repo

**Comment by thegasta** [comment]
@MarcoBuster smettila di fare il mona
By @OpenTelegramItaliaBot

**Comment by MarcoBuster** [comment]
@thegasta cos

**Comment by MarcoBuster** [comment]
Oddio! Posso bannare @thegasta da questa conversazione :D

**Comment by thegasta** [comment]
Certamente, puoi, ma poi ne subisci le conseguenze :joy:

**Comment by giuseppeM99** [comment]
**DEAL WHIT @thegasta**

**Comment by MarcoBuster** [comment]
Ma
Ok, torno a programmare gli altri bot per IATA. Zi badroni (@thegasta, @giuseppeM99 and @lollofra )

**Comment by giuseppeM99** [comment]
teach me mona
